---
- name: match sections
  pattern_match:
    regex: "hostname (.+)"
  register: hostname

- name: template entries
  json_template:
    template:
      - key: hostname
        value: "{{ hostname.matches.0 }}"
  register: nxos_system
  extend: cisco_nxos.config
  export: yes
